def readData(filepath="dat.csv"):
    """
    Reads the csv export generated by R.
    """

    lines = []

    with open("dat.csv", "r", encoding='windows-1252') as csv_data:
        for idx, row in enumerate(csv_data):
            if idx == 0:
                continue
            (timestamp, sender, message, media) = row.strip().split("##@@##")

            message = message[1:][:-1]
            sender = sender[1:][:-1]

            # TODO Parse emojis?
            # TODO Parse the timestamp. datetime package

            message_object = {
                "timestamp": timestamp,
                "sender": sender,
                "message": message,
                "media": media == "True"
            }

            lines.append(message_object)

    return lines
